# Generated by Django 5.1.4 on 2024-12-17 15:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50, 'First name cannot exceed 50 characters'), django.core.validators.MinLengthValidator(1, 'First name is required')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50, 'Last name cannot exceed 50 characters'), django.core.validators.MinLengthValidator(1, 'Last name is required')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50, 'First name cannot exceed 50 characters'), django.core.validators.MinLengthValidator(1, 'First name is required')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50, 'Last name cannot exceed 50 characters'), django.core.validators.MinLengthValidator(1, 'Last name is required')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_influencers', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok')], max_length=10)),
                ('username', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50, 'Username cannot exceed 50 characters'), django.core.validators.MinLengthValidator(1, 'Username is required')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_accounts', to='core.influencer')),
            ],
            options={
                'unique_together': {('influencer', 'platform', 'username')},
            },
        ),
    ]
